### ISSUE TITLE
Skill: (1) Integrate Twitter Bootstrap into Rails

### ISSUE THREAD

**Issue by snurby7** [snurby7/tc359_rails_final#3]
Should be implemented, gotta love that Bootstrap. Again, any suggestions you have for improvement, I'd love to hear!

Calling Mr. @chrisvfritz

**Comment by chrisvfritz** [comment]
It looks like this integration isn't quite right. Did you check out [the `bootstrap-sass` instructions for Rails](https://github.com/twbs/bootstrap-sass#a-ruby-on-rails)? It also looks like this second criterion isn't yet being met:

> You are overriding at least 3 Bootstrap variables (without using !important), for visible effect in your app

Also, if you want to become more comfortable with SCSS, [this skill](http://codekwondo.herokuapp.com/skills/44) is actually a suggested prerequisite on Codekwondo, so completing that one first would make this easier.

**Comment by snurby7** [comment]
Can you re-evaluate this one @chrisvfritz? I believe I've figured this one out.

**Comment by chrisvfritz** [comment]
This looks much better! Though I believe [this line](https://github.com/snurby7/tc359_rails_final/blob/master/app/assets/stylesheets/application.css.scss#L11) might be unnecessary. Try removing it and seeing if the glyphicons still work. If I'm remembering correctly, I think `@import "bootstrap";` imports *all* bootstrap components, including the glyphicons.

**Comment by snurby7** [comment]
You'd be correct, I think that glyphicons was giving me grief one day so I put that in there and it worked, but low and behold they were already there. The power of Ruby is a wonderful thing!

**Comment by chrisvfritz** [comment]
:+1: Looks great! This makes you the third student to have powered through for a 4.0 in this first week. Congratulations. :tada: :balloon:

That means there's no other work you have to do throughout the rest of the semester, if you don't want to! Of course, if you'd like to tackle other skills, I'd still be happy to give you feedback. And I'd also be happy to provide feedback on other webdev-related projects, if I could be helpful.

For example:

- At the beginning of the semester, you had an idea for a better CATA bus system that I'd be happy to help you develop. 
- Since you're a CS student, you could delve deeper into Ruby and/or JS/Coffee, if you wanted to beef up your skills there.
- Given your interest in mobile development, you may enjoy checking out [RubyMotion](http://www.rubymotion.com/), a toolchain for developing native, cross-platform mobile apps in Ruby.

Either way, let me know how I can be of service, if I can. :smiley:
