### ISSUE TITLE
(1) Allow users to sign up for new accounts in Rails

### ISSUE THREAD

**Issue by snurby7** [snurby7/tc359_rails_final#4]
Users are now able to create an account, should they choose to do so. However, I was unable to figure out how to throw the errors that can be caused when things are left blank, so any suggestions to accomplish that would be great!

Calling @chrisvfritz

**Comment by chrisvfritz** [comment]
There are a couple of things from stopping the errors from showing up. The errors themselves will usually be attached to a `@user` object, but we weren't using one in this case, so there was no way of telling the view that an error had occurred. You also used `redirect_to` instead of `render` when there was an error, which loads that action from scratch instead, making us lose `@user` if we had set it. `render` on the other hand, just renders the appropriate view. 

You can see a list of changes I would make to fix this below:

``` diff
diff --git a/app/controllers/users_controller.rb b/app/controllers/users_controller.rb
index 7ca0b07..3eb7f8b 100644
--- a/app/controllers/users_controller.rb
+++ b/app/controllers/users_controller.rb
@@ -1,15 +1,16 @@
 class UsersController < ApplicationController

   def new
+    @user = User.new
   end

   def create
-    user = User.new(user_params)
-    if user.save
-      session[:user_id] = user.id
+    @user = User.new(user_params)
+    if @user.save
+      session[:user_id] = @user.id
       redirect_to '/'
     else
-      redirect_to '/signup'
+      render :new
     end
   end

diff --git a/app/views/users/new.html.erb b/app/views/users/new.html.erb
index 5df5aaa..b724014 100644
--- a/app/views/users/new.html.erb
+++ b/app/views/users/new.html.erb
@@ -1,6 +1,6 @@
 <h1>Create Account</h1>

-<%= simple_form_for :user, url: '/users', defaults: { input_html: { class: 'form-vertical' } } do |f| %>
+<%= simple_form_for @user, defaults: { input_html: { class: 'form-vertical' } } do |f| %>
   <%= f.error_notification %>
   <%= f.input :email, required: true, input_html: { class: 'special' } %>
   <%= f.input :password, required: true, input_html: { maxlength: 20 } %>
```

**Comment by snurby7** [comment]
Now we're talking!! That gives me the errors I was looking for!! Thank you!! Check it out and let me know if there's anything else left

**Comment by chrisvfritz** [comment]
:+1: It looks great!
